//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#ifndef _NETDUINOAPPLICATION1_H_
#define _NETDUINOAPPLICATION1_H_

#include <TinyCLR_Interop.h>


extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_NetduinoApplication1;

#endif  //_NETDUINOAPPLICATION1_H_
